name: Deploy Web App

on:
    push:
        branches: ["main"]

permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests
          
      - name: Download Online Resources
        run: python download_resources.py
    
      - run: ls

      - name: Move static files
        run: |
          mkdir build
          mv *.js build
          mv *.css build
          mv data.json build
          mv index.html build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.